import type { Achievement } from '../types';

export const ACHIEVEMENTS_CATALOG: Achievement[] = [
  // --- MOVE ---
  {
    id: 'move_first_walk',
    key: 'first_walk',
    category: 'move',
    tier: 'bronze',
    titleRu: 'Первый шаг',
    titleEn: 'First Step',
    descriptionRu: 'Совершите первую прогулку',
    descriptionEn: 'Complete your first walk',
    icon: 'footsteps',
    condition: 'walks_total >= 1',
    premium: false,
  },
  {
    id: 'move_10_walks',
    key: '10_walks',
    category: 'move',
    tier: 'silver',
    titleRu: 'Десять шагов',
    titleEn: 'Ten Walks',
    descriptionRu: 'Совершите 10 прогулок',
    descriptionEn: 'Complete 10 walks',
    icon: 'walk',
    condition: 'walks_total >= 10',
    premium: false,
  },
  {
    id: 'move_50_walks',
    key: '50_walks',
    category: 'move',
    tier: 'gold',
    titleRu: 'Марафонец',
    titleEn: 'Marathoner',
    descriptionRu: 'Совершите 50 прогулок',
    descriptionEn: 'Complete 50 walks',
    icon: 'trending-up',
    condition: 'walks_total >= 50',
    premium: false,
  },
  {
    id: 'move_10km',
    key: '10km',
    category: 'move',
    tier: 'silver',
    titleRu: '10 километров',
    titleEn: '10 Kilometers',
    descriptionRu: 'Пройдите суммарно 10 км',
    descriptionEn: 'Walk a total of 10 km',
    icon: 'navigate',
    condition: 'distance_total >= 10000',
    premium: false,
  },
  {
    id: 'move_100km',
    key: '100km',
    category: 'move',
    tier: 'diamond',
    titleRu: '100 километров',
    titleEn: '100 Kilometers',
    descriptionRu: 'Пройдите суммарно 100 км',
    descriptionEn: 'Walk a total of 100 km',
    icon: 'rocket',
    condition: 'distance_total >= 100000',
    premium: true,
  },

  // --- MOOD ---
  {
    id: 'mood_first',
    key: 'first_mood',
    category: 'mood',
    tier: 'bronze',
    titleRu: 'Первая эмоция',
    titleEn: 'First Feeling',
    descriptionRu: 'Отметьте своё настроение впервые',
    descriptionEn: 'Log your mood for the first time',
    icon: 'happy',
    condition: 'moods_total >= 1',
    premium: false,
  },
  {
    id: 'mood_20',
    key: '20_moods',
    category: 'mood',
    tier: 'silver',
    titleRu: 'Чувственный',
    titleEn: 'Mindful',
    descriptionRu: 'Отметьте настроение 20 раз',
    descriptionEn: 'Log your mood 20 times',
    icon: 'heart',
    condition: 'moods_total >= 20',
    premium: false,
  },

  // --- RHYTHM ---
  {
    id: 'rhythm_streak_3',
    key: 'streak_3',
    category: 'rhythm',
    tier: 'bronze',
    titleRu: 'Три дня подряд',
    titleEn: 'Three Days',
    descriptionRu: 'Серия прогулок 3 дня подряд',
    descriptionEn: '3-day walking streak',
    icon: 'flame',
    condition: 'streak >= 3',
    premium: false,
  },
  {
    id: 'rhythm_streak_7',
    key: 'streak_7',
    category: 'rhythm',
    tier: 'silver',
    titleRu: 'Неделя ритма',
    titleEn: 'Week of Rhythm',
    descriptionRu: 'Серия прогулок 7 дней подряд',
    descriptionEn: '7-day walking streak',
    icon: 'flame',
    condition: 'streak >= 7',
    premium: false,
  },
  {
    id: 'rhythm_streak_30',
    key: 'streak_30',
    category: 'rhythm',
    tier: 'diamond',
    titleRu: 'Месяц силы',
    titleEn: 'Month of Power',
    descriptionRu: 'Серия прогулок 30 дней подряд',
    descriptionEn: '30-day walking streak',
    icon: 'diamond',
    condition: 'streak >= 30',
    premium: true,
  },

  // --- SLEEP ---
  {
    id: 'sleep_first',
    key: 'first_sleep',
    category: 'sleep',
    tier: 'bronze',
    titleRu: 'Первый сон',
    titleEn: 'First Sleep',
    descriptionRu: 'Запишите первый сон',
    descriptionEn: 'Log your first sleep entry',
    icon: 'moon',
    condition: 'sleep_total >= 1',
    premium: false,
  },
  {
    id: 'sleep_14',
    key: '14_sleeps',
    category: 'sleep',
    tier: 'gold',
    titleRu: 'Две недели снов',
    titleEn: 'Two Weeks',
    descriptionRu: 'Запишите сон 14 раз',
    descriptionEn: 'Log sleep 14 times',
    icon: 'bed',
    condition: 'sleep_total >= 14',
    premium: false,
  },

  // --- MEMORY ---
  {
    id: 'memory_first_habit',
    key: 'first_habit',
    category: 'memory',
    tier: 'bronze',
    titleRu: 'Первая привычка',
    titleEn: 'First Habit',
    descriptionRu: 'Создайте первую привычку',
    descriptionEn: 'Create your first habit',
    icon: 'checkbox',
    condition: 'habits_total >= 1',
    premium: false,
  },
  {
    id: 'memory_habit_7',
    key: 'habit_streak_7',
    category: 'memory',
    tier: 'gold',
    titleRu: 'Неделя дисциплины',
    titleEn: 'Discipline Week',
    descriptionRu: 'Выполняйте привычки 7 дней подряд',
    descriptionEn: 'Complete habits for 7 days straight',
    icon: 'trophy',
    condition: 'habit_streak >= 7',
    premium: false,
  },
];

export const TIER_CONFIG: Record<string, { emoji: string; color: string }> = {
  bronze: { emoji: '🥉', color: '#CD7F32' },
  silver: { emoji: '🥈', color: '#C0C0C0' },
  gold: { emoji: '🥇', color: '#FFD700' },
  diamond: { emoji: '💎', color: '#B9F2FF' },
};
