// ============================================
// Waygo — Dynamic Theme Matrix
// Like iPhone dynamic wallpapers — light→dark through the day
// ============================================

import type { ThemeColors, TimeBucket } from '../types';
import { palette } from './tokens';

// Base themes by time of day (weather modifiers applied separately)
export const timeThemes: Record<TimeBucket, ThemeColors> = {
  morning: {
    bgPrimary: palette.morningBg,
    bgSecondary: palette.morningBgSec,
    surfaceCard: palette.morningSurface,
    surfaceCardAlt: palette.morningSurfaceAlt,
    textPrimary: palette.morningText,
    textSecondary: palette.morningTextSec,
    textInverse: '#FFFFFF',
    accent: palette.morningAccent,
    accentBright: palette.morningAccentBright,
    accentMuted: palette.morningAccentMuted,
    accentMood: '#F5C98A',
    accentRhythm: '#FDE68A',
    accentMemory: '#FED7AA',
    stroke: palette.morningStroke,
    tabBarBg: palette.morningSurface,
    tabBarActive: palette.morningAccent,
    tabBarInactive: palette.morningTextSec,
    statusBarStyle: 'dark-content',
    greeting: 'morning',
    greetingEmoji: '🌅',
    tipStyle: 'motivating',
  },
  day: {
    bgPrimary: palette.dayBg,
    bgSecondary: palette.dayBgSec,
    surfaceCard: palette.daySurface,
    surfaceCardAlt: palette.daySurfaceAlt,
    textPrimary: palette.dayText,
    textSecondary: palette.dayTextSec,
    textInverse: '#FFFFFF',
    accent: palette.dayAccent,
    accentBright: palette.dayAccentBright,
    accentMuted: palette.dayAccentMuted,
    accentMood: '#A7F3D0',
    accentRhythm: '#6EE7B7',
    accentMemory: '#BAE6FD',
    stroke: palette.dayStroke,
    tabBarBg: palette.daySurface,
    tabBarActive: palette.dayAccent,
    tabBarInactive: palette.dayTextSec,
    statusBarStyle: 'dark-content',
    greeting: 'day',
    greetingEmoji: '☀️',
    tipStyle: 'energetic',
  },
  evening: {
    bgPrimary: palette.eveningBg,
    bgSecondary: palette.eveningBgSec,
    surfaceCard: palette.eveningSurface,
    surfaceCardAlt: palette.eveningSurfaceAlt,
    textPrimary: palette.eveningText,
    textSecondary: palette.eveningTextSec,
    textInverse: '#FFFFFF',
    accent: palette.eveningAccent,
    accentBright: palette.eveningAccentBright,
    accentMuted: palette.eveningAccentMuted,
    accentMood: '#FECDD3',
    accentRhythm: '#FDA4AF',
    accentMemory: '#FDE68A',
    stroke: palette.eveningStroke,
    tabBarBg: palette.eveningSurface,
    tabBarActive: palette.eveningAccent,
    tabBarInactive: palette.eveningTextSec,
    statusBarStyle: 'dark-content',
    greeting: 'evening',
    greetingEmoji: '🌇',
    tipStyle: 'relaxing',
  },
  night: {
    bgPrimary: palette.nightBg,
    bgSecondary: palette.nightBgSec,
    surfaceCard: palette.nightSurface,
    surfaceCardAlt: palette.nightSurfaceAlt,
    textPrimary: palette.nightText,
    textSecondary: palette.nightTextSec,
    textInverse: '#0C0B14',
    accent: palette.nightAccent,
    accentBright: palette.nightAccentBright,
    accentMuted: palette.nightAccentMuted,
    accentMood: '#C4B5FD',
    accentRhythm: '#A78BFA',
    accentMemory: '#818CF8',
    stroke: palette.nightStroke,
    tabBarBg: 'rgba(12, 11, 20, 0.95)',
    tabBarActive: palette.nightAccent,
    tabBarInactive: palette.nightTextSec,
    statusBarStyle: 'light-content',
    greeting: 'night',
    greetingEmoji: '🌙',
    tipStyle: 'calm',
  },
};

export function getDefaultTheme(): ThemeColors {
  return timeThemes.day;
}
